### ISSUE TITLE
Deployment: Ahead of time build failed to complete

### ISSUE THREAD

**Issue by epikoder** [denoland/fresh#2177] opened 2023-12-15 22:46 UTC
Ahead of time build is stock when running `deno task build`

**Expected**
Exit on completion

**Behviour**
Stock on this line
```
Assets written to: /app/_fresh
````

From the screenshot the left is Docker image `denoland/deno:1.38.3` while the right is host machine,
I've also tried `denoland/deno:1.39.0`

<img width="1442" alt="Screenshot 2023-12-15 at 11 22 33 PM" src="https://github.com/denoland/fresh/assets/39457512/a251a130-0cd5-430a-baeb-5ce342e7d1a7">

Here's my Dockerfile
```
FROM denoland/deno:1.38.3

ARG GIT_REVISION
ARG DATABASE_HOST=${DATABASE_HOST}
ARG DATABASE_PORT=${DATABASE_PORT}
ARG DATABASE_NAME=${DATABASE_NAME}
ARG DATABASE_USER=${DATABASE_USER}
ARG DATABASE_PASSWORD=${DATABASE_PASSWORD}

ENV DENO_DEPLOYMENT_ID=${GIT_REVISION}

WORKDIR /app

COPY . .
RUN deno task build \
    deno cache main.ts

EXPOSE 8000

CMD ["run", "-A", "main.ts"]
```

**Comment by BrunoBernardino** [comment] 2024-02-26 20:11
I'm not having this problem with Deno `1.41.0`, here's my `Dockerfile` in case it helps:

```dockerfile
FROM denoland/deno:alpine-1.41.0

EXPOSE 8000

WORKDIR /app

ADD . /app

RUN rm -fr node_modules _fresh 

RUN deno task build

RUN chown -R deno:deno /app /deno-dir

USER deno

RUN deno cache --reload main.ts

CMD ["run", "--allow-all", "main.ts"]
```

**Comment by marvinhagemeister** [comment] 2024-03-12 11:18
There is likely something that prevents the process from exciting. This usually happens when you're using Deno KV or Deno Queues in build mode.

Duplicate of https://github.com/denoland/fresh/issues/2240

**Closed as completed by marvinhagemeister** 2024-03-12 11:18 UTC
