### ISSUE TITLE
`Duplicate class in <html></html> when use className`

### ISSUE THREAD

**Issue by afifurrohman-id** [denoland/fresh#1655] opened 2023-08-17 04:31 UTC
# Duplicate class when use `className` inside `<html></html>` 

```tsx
<html className='bg-slate-800'>
</html>
```

**In Devtools**
```html
<html class='bg-slate-800 bg-slate-800'>
</html>
```

# `className` or `class` not work in `<body></body>`

```tsx
<body className='bg-slate-800'>
</body>
```

**In Devtools**
```html
<html>
...
   <body>
  </body>
</html>
```

**Comment by marvinhagemeister** [comment] 2023-08-17 05:09
I'm unable to reproduce that on my end. I only have on class on `<html>`. Can you share a GitHub repo where the problem can be reproduced?

The second part of not being able to add a class to `<body>` is fixed by https://github.com/denoland/fresh/pull/1648 which will be part of the next release.

**Comment by afifurrohman-id** [comment] 2023-08-17 07:45
> I'm unable to reproduce that on my end. I only have on class on `<html>`. Can you share a GitHub repo where the problem can be reproduced?
> 
> The second part of not being able to add a class to `<body>` is fixed by #1648 which will be part of the next release.

Using fresh project  from scratch

**Comment by marvinhagemeister** [comment] 2023-08-17 07:55
Looks like the crucial variable to reproduce this issue is that the `twind` plugin must be used. With that enabled I can reproduce the issue.

**Comment by marvinhagemeister** [comment] 2023-08-17 08:03
That issue seems to only occur when `className` is used instead of `class`

**Closed as completed** 2023-08-17 11:01 UTC
Labels: bug
