### ISSUE TITLE
Fresh website search island is broken

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/fresh#1463] opened 2023-07-14 10:34 UTC
Today, I couldn't search anything in the document. When I open devtool, I saw something like this:

![image](https://github.com/denoland/fresh/assets/68631458/d6943bb3-d2f2-4cdc-96b6-fb0fbf8f42c6)

I'm not sure if it is relates to this component: https://github.com/denoland/fresh/blob/main/www/islands/SearchButton.tsx

No idea how to fix this.

(The island on both FF & Chrome is not working)

**Comment by deer** [comment] 2023-07-14 10:47
I think this is a duplicate of https://github.com/denoland/fresh/issues/1441.

**Comment by marvinhagemeister** [comment] 2023-07-14 11:01
Yup,, it's a duplicate of #1441 . I haven't figured out yet why it breaks. It something during transpilation goes wrong as the input source code looks correct.

**Closed as completed by marvinhagemeister** 2023-07-14 11:01 UTC
