### ISSUE TITLE
NPM specifiers?

### ISSUE THREAD

**Issue by jimisaacs** [denoland/fresh#974] opened 2023-01-09 18:24 UTC
Does this work? I tried replacing the esm.sh examples with npm specifiers, but it seems to still be expected for esbuild. Can it work with esbuild?

**Comment by jimisaacs** [comment] 2023-01-09 18:27
Seems related: https://github.com/lucacasonato/esbuild_deno_loader/issues/29

**Comment by lucacasonato** [comment] 2023-01-10 12:38
Closing as a duplicate of https://github.com/denoland/fresh/issues/978

**Closed as not planned by lucacasonato** 2023-01-10 12:38 UTC
