### ISSUE TITLE
Add functionality to override default <HTML> tags

### ISSUE THREAD

**Issue by jmcelreavey** [denoland/fresh#487] opened 2022-07-09 15:20 UTC
Apologies if there's a template I should be using but I could see anything

[Next.js has the ability ](https://nextjs.org/docs/advanced-features/custom-document) to specify a `_document.tsx` file which allows for covering the <HTML> and <Body> tags as well as salting the document with any additional content which may be required. 

This would allow for custom styling to be applied at a top level.

**Comment by harrel56** [comment] 2022-07-09 23:35
Duplicate of #338

**Comment by lucacasonato** [comment] 2022-07-12 13:37
Closing as a duplicate.

**Closed as completed by lucacasonato** 2022-07-12 13:37 UTC
