### ISSUE TITLE
localStorage in Island,  `SyntaxError: "[object Object]" is not valid JSON`

### ISSUE THREAD

**Issue by afifurrohman-id** [denoland/fresh#1412] opened 2023-07-06 00:53 UTC
i'm trying parse JSON in localStorage in **Island**, but going error

```ts
JSON.parse(localStorage.getItem('some_json')!)
```

Why island prerender in server?, this error is on terminal, not browser console.

**Comment by deer** [comment] 2023-07-12 06:49
Can we close this as a duplicate of https://github.com/denoland/fresh/issues/975?

**Comment by marvinhagemeister** [comment] 2023-07-12 07:12
Good idea, #975 describes the use case already.

**Closed as completed by marvinhagemeister** 2023-07-12 07:12 UTC
