### ISSUE TITLE
Error - Cannot find name 'React'. Did you mean 'preact'? deno-ts(2552)

### ISSUE THREAD

**Issue by gmunumel** [denoland/fresh#788] opened 2022-09-22 16:58 UTC
Hello, 

After updated to version **1.1** I started getting errors in my files. The first error was related to: `JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists` which I solved doing: https://github.com/lampewebdev/deno-jsx-test. 

But now I got the error: `Cannot find name 'React'. Did you mean 'preact'?`, which is very annoying. I tried to reopen _VSCode_ many times but no luck.

If I start a project from scratch it does work: `deno run -A -r https://fresh.deno.dev my-app`

Any suggestion?

```
deno 1.25.0 (release, x86_64-pc-windows-msvc)
v8 10.6.194.5
typescript 4.7.4
```

**deno.json:**
```
{
  "tasks": {
    "start": "deno run -A --watch=static/,routes/ dev.ts"
  },
  "importMap": "./import_map.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  }
}
```

**.vscode/settings.json:**
```
{
  "deno.enable": true,
  "deno.unstable": false,
  "deno.lint": true,
  "editor.defaultFormatter": "denoland.vscode-deno",
  "deno.importMap": "./web/import_map.json",
  "deno.config": "./web/tsconfig.json"
}
```

![Screenshot 2022-09-22 185608](https://user-images.githubusercontent.com/276168/191807199-dc5cf079-04d7-42af-8e7c-d626730cc9d9.png)

**Comment by garyhe0780** [comment] 2022-09-23 02:25
Can you share your `deno.json` in your project? `Fresh 1.1` use automatic mode JSX by default

check more details [here](https://deno.com/blog/fresh-1.1#automatic-jsx)

**Comment by gmunumel** [comment] 2022-09-23 05:23
@garyhe0780 , updated my OP

**Comment by MoaathAlattas** [comment] 2022-09-25 05:48
> `"deno.config": "./web/tsconfig.json"`

`deno.config` should be the path of `deno.json` file:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/18528024/192130247-1fe90fb5-9d39-4005-8363-60a0249902f9.png">

**Comment by gmunumel** [comment] 2022-09-25 15:30
@MoaathAlattas , changed and now got: `JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`.

**Comment by gmunumel** [comment] 2022-09-26 16:45
A workaround to this problem is start a new project from scratch `deno run -A -r https://fresh.deno.dev from-scratch-app` and include all the files.

**Comment by gregorybchris** [comment] 2022-09-30 23:16
I'm new to deno, so to avoid issues getting started I just ran `deno upgrade --version 1.25.4` while hopefully version `1.26.0` is being patched.

**Comment by ryota-murakami** [comment] 2022-10-24 14:37
I got same error within new fresh project.

deno.json
```json
{
  "tasks": {
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "lint": "deno lint",
    "fmt": "deno fmt"
  },
  "importMap": "./import_map.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  }
}


```

<img width="995" alt="Screen Shot 2022-10-24 at 23 36 09" src="https://user-images.githubusercontent.com/5501268/197552591-3a3e6d15-4a44-4bf0-99dc-83d19a213550.png">

**Comment by ryota-murakami** [comment] 2022-10-25 12:12
I fixed this issue when I reset `deno.json` to project init default.

**Comment by jqueryisamonad** [comment] 2022-10-28 10:55
@ryota-murakami how did you do that? I get the same error on a fresh fresh 🙃 installation

**Comment by ryota-murakami** [comment] 2022-11-05 13:17
@gmunumel I turned off eslint/npm extension, then I fixed.

**Comment by lukepuplett** [comment] 2022-12-09 22:40
Got it.

You need to actually run your app, `deno task start`. If that doesn't work, then I also ran `deno cache --reload dev.ts`.

I'm very new to Deno and TypeScript/JS frontend stacks so I've no clue why this fixes it. Would love to how this all works... like what's the relationship between the TS language server I assume is running in the IDE and putting red marks on my code and... whatever happened when I ran the app for the first time?! Fascinating.

**Comment by avery-pierce** [comment] 2023-06-13 21:24
This just happened to me – I was able to resolve it by explicitly setting  the `deno.config` setting to the path of `deno.json` in `.vscode/settings.json`.

---

### `.vscode/settings.json`

```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.importMap": "./import_map.json",
  "editor.defaultFormatter": "denoland.vscode-deno",
  "deno.config": "./deno.json"
}
```

**Comment by lveillard** [comment] 2023-07-16 21:20
This, and installing `denoland.vscode-deno` pluggin, solved it for me.

> This just happened to me – I was able to resolve it by explicitly setting the `deno.config` setting to the path of `deno.json` in `.vscode/settings.json`.
> 
> ### `.vscode/settings.json`
> ```json
> {
>   "deno.enable": true,
>   "deno.lint": true,
>   "deno.importMap": "./import_map.json",
>   "editor.defaultFormatter": "denoland.vscode-deno",
>   "deno.config": "./deno.json"
> }
> ```

**Comment by marvinhagemeister** [comment] 2023-10-18 13:50
Marking this as a duplicate of https://github.com/denoland/deno/issues/20582 . Fresh uses Deno's built-in JSX support so there is nothing we can change on that on the Fresh side.

**Closed as completed by marvinhagemeister** 2023-10-18 13:50 UTC

**Comment by shujchen-oracle** [comment] 2024-04-09 05:05
Another possibility is you are having a pair `.ts` and `.tsx` files with same name, and you tried to import the component from the `.tsx` file. Compiler will complain this because it cannot find the right component from the `.ts` file.

Solution: rename your `.ts` or `.tsx` file, making them different ones.
