### ISSUE TITLE
Errors with arrays and nested islands

### ISSUE THREAD

**Issue by ssttevee** [denoland/fresh#783] opened 2022-09-19 16:28 UTC
There seems to be an issue relating to arrays, nested islands and `<></>`.

```
main.ts:9 Uncaught TypeError: Cannot read properties of undefined (reading 'nextSibling')
    at createRootFragment (main.ts:9:49)
    at walk (main.ts:46:9)
    at walk (main.ts:61:14)
    at walk (main.ts:62:13)
    at revive (main.ts:64:3)
```

I created a minimal project for reproducing this error: https://github.com/ssttevee/fresh-map-error-repro

There is actually another error in that repo when `<AnotherIsland/>` is deleted from `islands/List.tsx` and the button is pressed:

```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.insert (http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/main.js:43:1484)
    at J (http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/chunk-ABNOCSMY.js:1:2860)
    at G (http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/chunk-ABNOCSMY.js:1:2303)
    at W (http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/chunk-ABNOCSMY.js:1:5976)
    at G (http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/chunk-ABNOCSMY.js:1:2103)
    at W (http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/chunk-ABNOCSMY.js:1:5976)
    at http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/chunk-ABNOCSMY.js:1:1462
    at Array.some (<anonymous>)
    at D (http://localhost:8000/_frsh/js/4cc3143a-e588-47d5-8cfb-8266ea920d73/chunk-ABNOCSMY.js:1:1360)
```

Both of these errors can be easily overcome by just changing `<></>` to `<div></div>`, but that is unclear from the message.

**Comment by lucacasonato** [comment] 2022-09-21 15:04
Same root cause as #502. Closing as duplicate.

**Closed as not planned by lucacasonato** 2022-09-21 15:04 UTC
