### ISSUE TITLE
Custom page for any kind of response

### ISSUE THREAD

**Issue by comatory** [denoland/fresh#1014] opened 2023-02-02 21:42 UTC
I have a handler that can respond with `400` or other HTTP status codes but when I tried creating `routes/_400.tsx` it doesn't render the template.

My code looks something like this:

```
      if (error instanceof InvalidInputError) {
        return new Response(null, {
          status: 400,
          headers: new Headers({
            location: new URL(req.url).origin,
          }),
        });
      }
```

Where `InvalidInputError` is my custom error. In network dev tools I see the status is indeed `400`. My route resides in a subfolder, is that a problem?

**Comment by marvinhagemeister** [comment] 2023-11-06 16:23
Closing as duplicate of https://github.com/denoland/fresh/issues/556 . We only support `_404.tsx` and `_500.tsx` at the moment. The linked ticket is a feature request to expand that to more status codes.

**Closed as completed by marvinhagemeister** 2023-11-06 16:23 UTC
