### ISSUE TITLE
Redirect to the 404 page from inside handler

### ISSUE THREAD

**Issue by omar2205** [denoland/fresh#508] opened 2022-07-15 13:41 UTC
Is there a way to "abort" and use the _404 or _500 pages?

ex:
```ts
if (checkPost(1)) return ctx.render()
abort(404, 'This post was deleted')
```

**Comment by lj-n** [comment] 2022-07-15 14:06
I think this is not possible yet, see #251

**Comment by omar2205** [comment] 2022-07-15 14:36
Yeah, in the meantime, I created this hacky abort

```ts
// utils/abort.tsx
/** @jsx h */
import { h } from 'preact'
import { renderToString } from 'https://esm.sh/v87/preact-render-to-string@5.2.0'

const AbortPage = ({ p }) => <h1>{p.code} {p.err}</h1>

export const abort = (code: number, err: string) => {
  const body = renderToString(<AbortPage p={{code, err}} />)
  return new Response(body, {
    status: code,
    headers: {
      'Content-Type': 'text/html'
    }
  })
}
```

**Comment by lucacasonato** [comment] 2022-08-09 20:01
Duplicate of #484

**Closed as completed by lucacasonato** 2022-08-09 20:01 UTC
