### ISSUE TITLE
trailingSlash router option is not working anymore

### ISSUE THREAD

**Issue by cbinzer** [denoland/fresh#1785] opened 2023-09-17 14:28 UTC
Hi,

I updated my application from Fresh 1.4.2 to 1.4.3 and the trailingSlash option in the router config is not working anymore. Now I will be redirected to the route without the trailingSlash.

Regards
Christian

**Comment by marvinhagemeister** [comment] 2023-09-18 15:54
How can we reproduce the error? Do you have a reproduction case? We have some tests that ensure that the trailing slash is appended, but it looks like it's missing a case.

**Comment by cbinzer** [comment] 2023-09-18 18:54
Hi Marvin,

I created the following repository: [https://github.com/cbinzer/fresh-trailing-slash-bug](https://github.com/cbinzer/fresh-trailing-slash-bug). In the main.ts I set trailingSlash to true. If you open http://localhost:8000/about/ you will be redirected to http://localhost:8000/about.

**Comment by marvinhagemeister** [comment] 2023-09-18 20:23
Sweet, thanks for sharing a reproduction case. Can confirm that this issue exists in Fresh `1.4.3`. I couldn't reproduce it with the latest `main`, so I did a `git bisect` and it turns out that this issue here is already fixed by #1764 . I'm not sure when the next Fresh release is going to be, but in the meantime you can go with the `canary` version and use the fixed version today if that fits your requirements. The process on how to do that is documented here https://fresh.deno.dev/docs/canary/examples/using-fresh-canary-version

**Closed as completed by marvinhagemeister** 2023-09-18 20:23 UTC

**Comment by cbinzer** [comment] 2023-09-19 06:39
Thats ok for me. I can stay at 1.4.2. I'am looking forward for the next Fresh version :-)
