### ISSUE TITLE
example not working on `https://fresh.deno.dev`

### ISSUE THREAD

**Issue by scarf005** [denoland/fresh#1048] opened 2023-02-25 05:12 UTC
![Peek 2023-02-25 14-10](https://user-images.githubusercontent.com/54838975/221339604-0bbde846-faac-4a43-9cfd-3fca71a3e67a.gif)

[example](https://fresh.deno.dev/#example) counter app is unclickable. using `firefox 111.0b5 (64-bit)` on ubuntu 22.10

**Comment by scarf005** [comment] 2023-02-27 10:03
oh, well, it works now and can't reproduce either.
![image](https://user-images.githubusercontent.com/54838975/221533827-fba75ab2-2d88-406f-a1de-a13e56d7d04f.png)

**Comment by arnauorriols** [comment] 2023-03-23 09:46
I had the same issue. Cleaning the cache solved the issue. Reopening because cache should be invalidated automatically when necessary.

**Comment by kt3k** [comment] 2023-03-26 11:47
I observed the same issue. The same non-existent chunk javascript was requested even when I explicitly reloaded the page.

Disabling the cache explicitly from devtools solved the issue

**Comment by hashrock** [comment] 2023-03-28 05:28
If anyone can speculate as to why this happens, it would be helpful if you could comment. So far I have no idea what causes this to happen.
From the phenomenon, it seems that the cache of island's JS files is out of date, but the URL should be changed with each build.

**Comment by marvinhagemeister** [comment] 2023-06-16 10:29
This issue happens when the JavaScript wasn't loaded in the client. If you disable JavaScript in your browsers DevTools you can reproduce the exact behavior. So the question that I don't have an answer to is "why wasn't the JS loaded?" :S

**Comment by AffogatoAlCaffe** [comment] 2023-06-26 21:53
Just a guess
Maybe due to your your proxies and the immutable directive: https://httpwg.org/specs/rfc8246.html#about-intermediaries
Browser Support:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#browser_compatibility

**Comment by marvinhagemeister** [comment] 2023-09-05 10:18
I'm closing this, since I think what likely happened is that the JIT build took too long. This is the exact problem the AOT build solves.

**Closed as completed by marvinhagemeister** 2023-09-05 10:18 UTC
Labels: bug, needs repro
