### ISSUE TITLE
Input with type=submit inside partial does not submit its own value

### ISSUE THREAD

**Issue by Sleepful** [denoland/fresh#2566] opened 2024-07-02 07:20 UTC
consider:

```tsx

      <form
        f-partial="/partial/car_type"
        method="post"
      />
            <input
              type="submit"
              class="hidden"
              name="car"
              value="a"/>
```
when this input is clicked and the form is submitted, the `req.formData();` should contain the value `{ car: "a"}`, but it does not. It is empty instead.

**Comment by marvinhagemeister** [comment] 2024-07-02 07:34
Is the input inside the form? In the snippet the `<form />` tag is self closing or is that a copy & paste error here and the form encapsulates the input element in your app?

**Comment by Sleepful** [comment] 2024-07-02 07:54
@marvinhagemeister copy & paste error, my bad. Here is a better copy/paste

```ts
            <form
              f-partial={`/load_version`}
              method="post"
            >
              <input
                type="submit"
                name="version"
                value="saved"
                class="m-2 bg-blue-600"
              />
            </form>
```

then in the route:

```ts
  async POST(req, ctx) {
    const form = await req.formData();
    const formValues = Object.fromEntries(form.entries());
    console.log({ formValues });
	// prints empty object for formValues, if I remove partial navigation 
 	// and use a standard `action` route, it does display the value though 
```

**Comment by marvinhagemeister** [comment] 2024-07-02 20:34
Good news: Just took a look at this and it is already fixed in `main`.  I'm not sure which exact commit resolved it, but I cannot reproduce it there anymore 🎉

**Closed as completed by marvinhagemeister** 2024-07-02 20:34 UTC
Labels: bug
