### ISSUE TITLE
BUG: support non-ASCII island filename

### ISSUE THREAD

**Issue by secext2022** [denoland/fresh#1458] opened 2023-07-13 08:09 UTC
When use non-ASCII for island filename, you get a 404 error:

island file: `islands/a666/测试.tsx`

```
> curl -v "http://localhost:8000/_frsh/js/40f967fead6ba6ab02099fe32910ecb1ec092735/island-a666%e6%b5%8b%e8%af%95.js"
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /_frsh/js/40f967fead6ba6ab02099fe32910ecb1ec092735/island-a666%e6%b5%8b%e8%af%95.js HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< vary: Accept-Encoding
< content-length: 0
< date: Thu, 13 Jul 2023 08:06:45 GMT
< 
* Connection #0 to host localhost left intact
```

To fix this BUG, a few lines of code has to change:

```patch
> git diff .
diff --git a/vendor/fresh-1.2.0/src/server/context.ts b/vendor/fresh-1.2.0/src/server/context.ts
index 16fead4..55ab56b 100644
--- a/vendor/fresh-1.2.0/src/server/context.ts
+++ b/vendor/fresh-1.2.0/src/server/context.ts
@@ -277,7 +277,7 @@ export class ServerContext {
       }
       const path = url.substring(baseUrl.length).substring("islands".length);
       const baseRoute = path.substring(1, path.length - extname(path).length);
-      const name = sanitizeIslandName(baseRoute);
+      const name = sanitizeIslandName(decodeURI(baseRoute));
       const id = name.toLowerCase();
       if (typeof module.default !== "function") {
         throw new TypeError(
@@ -770,7 +770,7 @@ export class ServerContext {
   #bundleAssetRoute = (): router.MatchHandler => {
     return async (_req, _ctx, params) => {
       const snapshot = await this.#buildSnapshot();
-      const contents = snapshot.read(params.path);
+      const contents = snapshot.read(encodeURI(params.path));
       if (!contents) return new Response(null, { status: 404 });
 
       const headers: Record<string, string> = {
```

After change, it works ok:

```
> curl -v "http://localhost:8000/_frsh/js/36058cca27170df8d00bda95964e9e72e9260280/island-a666%E6%B5%8B%E8%AF%95.js"
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /_frsh/js/36058cca27170df8d00bda95964e9e72e9260280/island-a666%E6%B5%8B%E8%AF%95.js HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 200 OK
< cache-control: public, max-age=604800, immutable
< content-type: application/javascript
< vary: Accept-Encoding
< content-length: 210
< date: Thu, 13 Jul 2023 08:05:51 GMT
< 
```

**Comment by marvinhagemeister** [comment] 2023-07-13 08:28
Duplicate of https://github.com/denoland/fresh/issues/1432 . The fix is already and `main` and will be included in the next release. The next release will likely go out today or tomorrow.

**Closed as completed by marvinhagemeister** 2023-07-13 08:28 UTC
