### ISSUE TITLE
www: ﻿﻿syntax highlighted code of the document site is broken when the page is moved

### ISSUE THREAD

**Issue by azu** [denoland/fresh#2329] opened 2024-02-22 04:52 UTC
The syntax highlighted code of the document site is broken when the page is moved.

![after](https://github.com/denoland/fresh/assets/19714/6cdf3ce0-d013-4817-9805-26140f2e7518)

> `;` and some spaces are missing

Some tokens are disappearred from the syntax highlighted code.

## Reproduce Step

https://github.com/denoland/fresh/assets/19714/77c1e477-8225-4ed3-b784-c71b3298db5f

1. visit ﻿https://fresh.deno.dev/docs/getting-started/form-submissions
2. click "Next Page"
3. click "Previous Page" on https://fresh.deno.dev/docs/getting-started/adding-interactivity
4. syntax highlighed code is something wrong

| Before | After |
| ------ | ----- |
| ![before](https://github.com/denoland/fresh/assets/19714/1e0bec5b-6d34-4dad-9ecd-c82d811d0bfc) | ![after](https://github.com/denoland/fresh/assets/19714/6cdf3ce0-d013-4817-9805-26140f2e7518) |

```diff
- import { Handlers, PageProps } from "$fresh/server.ts";
+ import { Handlers, PageProps } from "$fresh/server.ts"const
```

## Env

- OS: macOS 14.3.1
- Chrome: 123.0.6300.3（Official Build）dev （arm64）

**Comment by marvinhagemeister** [comment] 2024-02-22 07:16
Duplicate of https://github.com/denoland/fresh/issues/2322

**Closed as completed by marvinhagemeister** 2024-02-22 07:16 UTC
